// Code generated by ent, DO NOT EDIT.

package ent

import (
	"books/ent/book"
	"books/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescCreatedAt is the schema descriptor for created_at field.
	bookDescCreatedAt := bookFields[0].Descriptor()
	// book.DefaultCreatedAt holds the default value on creation for the created_at field.
	book.DefaultCreatedAt = bookDescCreatedAt.Default.(func() time.Time)
	// bookDescUpdatedAt is the schema descriptor for updated_at field.
	bookDescUpdatedAt := bookFields[1].Descriptor()
	// book.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	book.DefaultUpdatedAt = bookDescUpdatedAt.Default.(func() time.Time)
	// book.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	book.UpdateDefaultUpdatedAt = bookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookDescTitle is the schema descriptor for title field.
	bookDescTitle := bookFields[2].Descriptor()
	// book.DefaultTitle holds the default value on creation for the title field.
	book.DefaultTitle = bookDescTitle.Default.(string)
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[3].Descriptor()
	// book.DefaultAuthor holds the default value on creation for the author field.
	book.DefaultAuthor = bookDescAuthor.Default.(string)
	// bookDescPublicationYear is the schema descriptor for publication_year field.
	bookDescPublicationYear := bookFields[4].Descriptor()
	// book.DefaultPublicationYear holds the default value on creation for the publication_year field.
	book.DefaultPublicationYear = bookDescPublicationYear.Default.(func() time.Time)
	// book.UpdateDefaultPublicationYear holds the default value on update for the publication_year field.
	book.UpdateDefaultPublicationYear = bookDescPublicationYear.UpdateDefault.(func() time.Time)
	// bookDescIsDeleted is the schema descriptor for is_deleted field.
	bookDescIsDeleted := bookFields[5].Descriptor()
	// book.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	book.DefaultIsDeleted = bookDescIsDeleted.Default.(bool)
}
