-- Create "books" table
CREATE TABLE "books" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "title" character varying NULL DEFAULT '', "author" character varying NULL DEFAULT '', "publication_year" timestamptz NOT NULL, "is_deleted" boolean NULL DEFAULT false, PRIMARY KEY ("id"));
